//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWherrelz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public int ID { get; set; }
        public string accountNumber { get; set; }
        public string accountName { get; set; }
        public Nullable<int> currency { get; set; }
        public string creditAmount { get; set; }
        public string debitAmount { get; set; }
        public string remarks { get; set; }
        public System.DateTime createdOn { get; set; }
        public Nullable<int> userId { get; set; }
    }
}
